main:
  - name: Sobre mí
    pageRef: /
    weight: 10
  - name: Trayectoria
    pageRef: /experience
    weight: 20
  - name: Proyectos
    pageRef: /projects
    weight: 30
  - name: Publicaciones
    pageRef: /publication
    weight: 40
  - name: Blog
    pageRef: /blog
    weight: 50
